In [1]:
import itertools
import numpy as np

matrix = np.arange(16).reshape(4, 4)
print(matrix)

numbers = [0, 1, 2, 3]
combinations = list(itertools.combinations(numbers, 2))

print(combinations)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]


In [2]:
[matrix[r,c] for r,c in combinations]

[1, 2, 3, 6, 7, 11]

In [3]:
[matrix[r,c] for r,c in [(0,0), (1,1), (2,2), (3,3)]]

[0, 5, 10, 15]